# Generated by Django 5.0.4 on 2024-08-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("subscriptions", "0003_subscriptions_permissions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscriptions",
            new_name="Subscription",
        ),
    ]
