# Generated by Django 5.0.4 on 2024-08-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_subscription_created_subscription_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionprice",
            name="featured",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscriptionprice",
            name="order",
            field=models.IntegerField(default=1),
        ),
    ]
