# Generated by Django 5.0.4 on 2024-09-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notification_message_alter_notification_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
