# Generated by Django 5.0.4 on 2024-09-14 22:43

import hashid_field.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskResult",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="Name of the Task which was run",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Task Name",
                    ),
                ),
                (
                    "task_args",
                    models.TextField(
                        help_text="JSON representation of the positional arguments used with the task",
                        null=True,
                        verbose_name="Task Positional Arguments",
                    ),
                ),
                (
                    "task_kwargs",
                    models.TextField(
                        help_text="JSON representation of the named arguments used with the task",
                        null=True,
                        verbose_name="Task Named Arguments",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RECEIVED", "Received"),
                            ("STARTED", "Started"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("REVOKED", "Revoked"),
                            ("REJECTED", "Rejected"),
                            ("RETRY", "Retry"),
                            ("IGNORED", "Ignored"),
                        ],
                        default="PENDING",
                        help_text="Current state of the task being run",
                        max_length=50,
                        verbose_name="Task State",
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        default=None,
                        editable=False,
                        help_text="The data returned by the task.  Use content_encoding and content_type fields to read.",
                        null=True,
                        verbose_name="Result Data",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Datetime field when the task result was created in UTC",
                        verbose_name="Created DateTime",
                    ),
                ),
                (
                    "date_done",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datetime field when the task was completed in UTC",
                        verbose_name="Completed DateTime",
                    ),
                ),
                (
                    "traceback",
                    models.TextField(
                        blank=True,
                        help_text="Text of the traceback if the task generated one",
                        null=True,
                        verbose_name="Traceback",
                    ),
                ),
            ],
            options={
                "verbose_name": "task result",
                "verbose_name_plural": "task results",
                "ordering": ["-date_done"],
                "indexes": [
                    models.Index(
                        fields=["task_name"], name="aws_lambda_task_na_08aec9_idx"
                    ),
                    models.Index(
                        fields=["status"], name="aws_lambda_status_9b6201_idx"
                    ),
                    models.Index(
                        fields=["date_created"], name="aws_lambda_date_cr_f04a50_idx"
                    ),
                    models.Index(
                        fields=["date_done"], name="aws_lambda_date_do_f59aad_idx"
                    ),
                ],
            },
        ),
    ]
