# Generated by Django 5.0.4 on 2024-09-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws_tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskresult",
            name="task_args",
            field=models.JSONField(
                help_text="JSON representation of the positional arguments used with the task",
                null=True,
                verbose_name="Task Positional Arguments",
            ),
        ),
        migrations.AlterField(
            model_name="taskresult",
            name="task_kwargs",
            field=models.JSONField(
                help_text="JSON representation of the named arguments used with the task",
                null=True,
                verbose_name="Task Named Arguments",
            ),
        ),
        migrations.AlterField(
            model_name="taskresult",
            name="task_name",
            field=models.CharField(
                help_text="Name of the Task which was run",
                max_length=255,
                unique=True,
                verbose_name="Task Name",
            ),
        ),
    ]
