# Generated by Django 5.0.4 on 2024-09-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_thirdparty_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thirdparty",
            name="state",
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
