# Generated by Django 5.0.4 on 2024-09-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0009_alter_thirdparty_state"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="integration",
            name="unique_user_thirdparty",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="access_revoked",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="thirdparty",
            name="state",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
