# Generated by Django 5.0.4 on 2024-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0011_integration_id_token_alter_integration_refresh_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="access_token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="integration",
            name="id_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="integration",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
