# Generated by Django 5.0.4 on 2024-08-14 14:18

import django.db.models.deletion
import hashid_field.field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_subscription_stripe_id_alter_subscription_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPrice",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("usd", "USD"), ("euro", "EURO")],
                        default="usd",
                        max_length=15,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("month", "Monthly"),
                            ("year", "Yearly"),
                            ("day", "Daily"),
                            ("week", "Weekly"),
                        ],
                        default="month",
                        max_length=25,
                    ),
                ),
                ("trial_period_days", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("stripe_id", models.CharField(max_length=150, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.subscription",
                    ),
                ),
            ],
        ),
    ]
