# Generated by Django 5.0.4 on 2024-08-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_subscriptionprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
