# Generated by Django 5.0.4 on 2024-08-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0012_alter_subscriptionprice_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["order", "-updated"],
                "permissions": [
                    ("advanced", "Advanced Perm"),
                    ("pro", "Pro Perm"),
                    ("basic", "Basic Perm"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={
                "ordering": ["subscription__order", "order", "featured", "-updated"]
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="order",
            field=models.IntegerField(default=1),
        ),
    ]
