# Generated by Django 5.0.4 on 2024-08-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0016_usersubscription_stripe_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionprice",
            name="trial_period_days",
            field=models.IntegerField(default=0),
        ),
    ]
