# Generated by Django 5.0.4 on 2024-08-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0018_usersubscription_client_secret_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("incomplete", "Incomplete"),
                    ("incomplete_expired", "Incomplete Expired"),
                    ("trialing", "Trialing"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("canceled", "canceled"),
                    ("unpaid", "Unpaid"),
                    ("paused", "Paused"),
                ],
                default="active",
                max_length=30,
            ),
        ),
    ]
