# Generated by Django 5.0.4 on 2024-09-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0020_usersubscription_cancel_at_period_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionprice",
            name="interval",
            field=models.CharField(
                choices=[
                    ("month", "Monthly"),
                    ("year", "Yearly"),
                    ("day", "Daily"),
                    ("week", "Weekly"),
                ],
                default="month",
                max_length=50,
            ),
        ),
    ]
