# Generated by Django 5.0.4 on 2024-09-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0021_alter_subscriptionprice_interval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubscription",
            name="client_secret",
        ),
    ]
