# Generated by Django 5.0.4 on 2024-09-15 13:46

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_device_token_userprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useravatar",
            name="original",
            field=models.ImageField(
                null=True,
                storage=common.storages.PublicS3Boto3StorageWithCDN,
                upload_to=common.storages.UniqueFilePathGenerator("avatars"),
            ),
        ),
        migrations.AlterField(
            model_name="useravatar",
            name="thumbnail",
            field=models.ImageField(
                null=True,
                storage=common.storages.PublicS3Boto3StorageWithCDN,
                upload_to=common.storages.UniqueFilePathGenerator("avatars/thumbnails"),
            ),
        ),
    ]
