# Generated by Django 5.0.4 on 2024-09-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_alter_notification_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("UPDATE_PROFILE", "Update Profile"), ("DEFAULT", "Default")],
                max_length=64,
            ),
        ),
    ]
