# Generated by Django 5.0.4 on 2024-09-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_notification_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="message",
            new_name="description",
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="Notification title", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("UPDATE_PROFILE", "Update Profile"), ("DEFAULT", "Default")],
                default="DEFAULT",
                max_length=64,
            ),
        ),
    ]
