# Generated by Django 5.0.4 on 2024-08-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thirdparty",
            options={"verbose_name_plural": "Thirdparties"},
        ),
    ]
