# Generated by Django 5.0.4 on 2024-09-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_thirdparty_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="thirdparty",
            name="revoke_uri",
            field=models.URLField(blank=True, null=True),
        ),
    ]
