# Generated by Django 5.0.4 on 2024-09-08 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_thirdparty_revoke_uri"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Integrations",
            new_name="Integration",
        ),
        migrations.AlterField(
            model_name="thirdparty",
            name="scopes",
            field=models.TextField(help_text="Comma-separated scopes"),
        ),
        migrations.AddConstraint(
            model_name="integration",
            constraint=models.UniqueConstraint(
                fields=("user", "thirdparty"), name="unique_user_thirdparty"
            ),
        ),
    ]
