# Generated by Django 5.0.4 on 2024-09-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0007_alter_integration_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="thirdparty",
            name="state",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
