# Generated by Django 5.0.4 on 2024-09-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0010_remove_integration_unique_user_thirdparty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="id_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="integration",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
